- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 108000 #50 hrs # Corvax-RoleTime
    # Exodus-Better-Sec-Hiring-Start
    - !type:TraitsRequirement
      inverted: true
      traits:
      - Muted
      - Blindness
      - Narcolepsy
      - Pacifist
    # Exodus-Better-Sec-Hiring-End
  weight: 5
  startingGear: WardenGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: WardenGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: WardenPDA
    # Exodus-Loadout-Update-Start
    # ears: ClothingHeadsetSecurity
    # pocket1: WeaponPistolMk58
    # Exodus-Loadout-Update-End
  storage:
    back:
    - Flash
    # - MagazinePistol # Exodus-Loadout-Update

- type: chameleonOutfit
  id: WardenChameleonOutfit
  job: Warden
  hasMindShield: true
  equipment:
    head: ClothingHeadHatWarden
    mask: ClothingMaskGasSecurity
    outerClothing: ClothingOuterCoatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    neck: Dinkystar
    belt: ClothingBeltSecurity
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsJack
