name: RSI Validator

on:
  push:
    branches: [ staging, trying ]
  merge_group:
  pull_request:
    paths:
      - '**.rsi/**'

jobs:
  validate_rsis:
    name: Validate RSIs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Setup Submodule
        run: git submodule update --init
      # Exodus-Secrets-Start
      - name: Setup secrets
        env:
          SSH_KEY: ${{ secrets.SECRETS_PRIVATE_KEY }}
        if: ${{ env.SSH_KEY != '' }}
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SECRETS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "HOST *" > ~/.ssh/config
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          git clone git@github.com:space-exodus/secrets.git Secrets
          cp -R Secrets/Resources/Prototypes Resources/Prototypes/ExodusSecrets
          cp -R Secrets/Resources/Locale Resources/Locale/ru-RU/exodus-secrets
          cp -R Secrets/Resources/Textures Resources/Textures/ExodusSecrets
      # Exodus-Secrets-End
      - name: Pull engine updates
        uses: space-wizards/submodule-dependency@v0.1.5
      - name: Install Python dependencies
        run: |
          pip3 install --ignore-installed --user pillow jsonschema
      - name: Validate RSIs
        # Exodus-CLA-Start
        run: |
          python3 Schemas/validate_rsis.py Resources/
        # Exodus-CLA-End
